### ISSUE TITLE
sampling period

### ISSUE THREAD

**Issue by semajoel** [MarcelloYung/opcn2-Arduino#1]
Is there any development on control of the sampling period.
What is noticed is that the delay in the loop function affecting the sampling period printed in the serial.

**Comment by nmarcelo** [comment]
I think in this code it is not possible, since the histogram is captured in the loop.
The histogram must be captured in an independent function to avoid the delay due the others operations in the system. Thread approach could be adecuate for the sampling period control.
https://github.com/ivanseidel/ArduinoThread
